#!/usr/bin/env bash
# Capy Privacy — first-time setup: TLS, Caddyfile, .env
# Usage: ./init.sh   (from repo root; uses sudo for /etc/letsencrypt)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
CADDY_TEMPLATE="${ROOT}/Caddyfile.template"

# Install real cert + key files under /etc/letsencrypt/live/<name>/ (not symlinks) for Docker bind mounts.
install_cert() {
	local name="$1" cert="$2" key="$3"
	sudo mkdir -p "/etc/letsencrypt/live/${name}"
	sudo cp "$cert" "/etc/letsencrypt/live/${name}/fullchain.pem"
	sudo cp "$key" "/etc/letsencrypt/live/${name}/privkey.pem"
	sudo chmod 644 "/etc/letsencrypt/live/${name}/fullchain.pem"
	sudo chmod 600 "/etc/letsencrypt/live/${name}/privkey.pem"
}

# Self-signed TLS for bare IP (block page HTTPS). Installs under /etc/letsencrypt/live/<ip>/
gen_self_signed_ip() {
	local ip="$1"
	local d c k
	d="$(mktemp -d)"
	c="${d}/cert.pem"
	k="${d}/key.pem"
	if openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
		-keyout "$k" -out "$c" \
		-subj "/CN=${ip}" \
		-addext "subjectAltName=IP:${ip}" 2>/dev/null; then
		:
	else
		cat >"${d}/openssl.cnf" <<OPENSSL_CONF
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
CN = ${ip}
[v3_req]
subjectAltName = IP:${ip}
OPENSSL_CONF
		openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
			-keyout "$k" -out "$c" \
			-config "${d}/openssl.cnf" -extensions v3_req
	fi
	install_cert "$ip" "$c" "$k"
	rm -rf "$d"
}

guess_public_ip() {
	local ip=""
	ip="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || true)"
	if [[ -z "$ip" ]] && command -v hostname >/dev/null 2>&1; then
		ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
	fi
	echo "${ip:-}"
}

write_caddyfile() {
	local api_domain="$1" admin_domain="$2" dns_domain="$3" domain="$4" ip="$5"
	local out="${ROOT}/Caddyfile"
	if [[ ! -f "$CADDY_TEMPLATE" ]]; then
		echo "Missing Caddy template: ${CADDY_TEMPLATE}" >&2
		exit 1
	fi

	if ! command -v envsubst >/dev/null 2>&1; then
		echo "envsubst is required to render ${CADDY_TEMPLATE}. Install gettext (e.g. brew install gettext)." >&2
		exit 1
	fi

	API_DOMAIN="$api_domain" \
	ADMIN_DOMAIN="$admin_domain" \
	DNS_DOMAIN="$dns_domain" \
	DOMAIN="$domain" \
	IP_ADDRESS="$ip" \
		envsubst '${API_DOMAIN} ${ADMIN_DOMAIN} ${DNS_DOMAIN} ${DOMAIN} ${IP_ADDRESS}' \
			<"$CADDY_TEMPLATE" >"$out"
}

# --- prompts -----------------------------------------------------------------

read -rp "Server domain [localhost]: " DOMAIN
DOMAIN="${DOMAIN:-localhost}"

API_DOMAIN="api.${DOMAIN}"
ADMIN_DOMAIN="admin.${DOMAIN}"
DNS_DOMAIN="dns.${DOMAIN}"

if [[ "$DOMAIN" == "localhost" ]]; then
	IP_ADDRESS="127.0.0.1"
	echo "Using IP_ADDRESS=${IP_ADDRESS} (localhost mode)."
else
	GUESSED="$(guess_public_ip)"
	read -rp "Server IP [${GUESSED:-?}]: " IP_ADDRESS
	IP_ADDRESS="${IP_ADDRESS:-$GUESSED}"
	if [[ -z "$IP_ADDRESS" ]]; then
		echo "Could not determine IP; please run again and enter the server public IP." >&2
		exit 1
	fi
fi

# --- certificates ------------------------------------------------------------

if [[ "$DOMAIN" == "localhost" ]]; then
	if ! command -v mkcert >/dev/null 2>&1; then
		echo "mkcert is required for localhost TLS. Install e.g.:  brew install mkcert && mkcert -install" >&2
		exit 1
	fi
	mkcert -install >/dev/null 2>&1 || true
	for name in "${API_DOMAIN}" "${DNS_DOMAIN}" "${ADMIN_DOMAIN}" "localhost" "127.0.0.1"; do
		tmpd="$(mktemp -d)"
		mkcert -cert-file "${tmpd}/fullchain.pem" -key-file "${tmpd}/privkey.pem" "${name}"
		install_cert "${name}" "${tmpd}/fullchain.pem" "${tmpd}/privkey.pem"
		rm -rf "${tmpd}"
	done
else
	if ! command -v certbot >/dev/null 2>&1; then
		echo "certbot is required for Let's Encrypt. Install certbot on this host." >&2
		exit 1
	fi
	read -rp "Let's Encrypt email: " EMAIL
	if [[ -z "${EMAIL:-}" ]]; then
		echo "Email is required for certbot -agree-tos." >&2
		exit 1
	fi
	echo "Ensure ports 80 and 443 are free (e.g. podman compose down) before certbot runs."
	read -rp "Press Enter to continue..."
	for name in "${API_DOMAIN}" "${DNS_DOMAIN}" "${ADMIN_DOMAIN}" "${DOMAIN}"; do
		certbot certonly --standalone --non-interactive --agree-tos -m "${EMAIL}" -d "${name}"
		tmpd="$(mktemp -d)"
		# Dereference Certbot symlinks into real files for install_cert / Podman bind mounts
		sudo cat "/etc/letsencrypt/live/${name}/fullchain.pem" >"${tmpd}/fullchain.pem"
		sudo cat "/etc/letsencrypt/live/${name}/privkey.pem" >"${tmpd}/privkey.pem"
		chmod 644 "${tmpd}/fullchain.pem"
		chmod 600 "${tmpd}/privkey.pem"
		install_cert "${name}" "${tmpd}/fullchain.pem" "${tmpd}/privkey.pem"
		rm -rf "${tmpd}"
	done
	gen_self_signed_ip "${IP_ADDRESS}"
fi

write_caddyfile "${API_DOMAIN}" "${ADMIN_DOMAIN}" "${DNS_DOMAIN}" "${DOMAIN}" "${IP_ADDRESS}"

API_SECRET="$(openssl rand -base64 32)"
cat >"${ROOT}/.env" <<ENV
# Generated by init.sh
DOMAIN=${DOMAIN}
IP_ADDRESS=${IP_ADDRESS}
API_SECRET=${API_SECRET}
ENV

echo ""
echo "Done."
echo "  DOMAIN=${DOMAIN}  IP_ADDRESS=${IP_ADDRESS}"
echo "  TLS material: /etc/letsencrypt/live/<hostname>/ (mounted into capy_front and capy_core)"
echo "  Wrote ${ROOT}/.env and ${ROOT}/Caddyfile"
echo ""
echo "Next:  podman compose up -d --build"
echo "Note: Rebuild capy_front after DOMAIN changes — VITE_API_URL is http://api.<DOMAIN>/ from compose (set https in compose if you need TLS for the API in the browser)."
