#!/usr/bin/env bash
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SSL_DIR="${ROOT}/resources/ssl"
ENV_FILE="${ROOT}/.env"

echo "=============================================="
echo "  Capy Privacy - First time setup"
echo "=============================================="
echo ""

echo "How will Capy Privacy be used?"
echo "  1) Local only (LAN) - HTTP for UI/API, self-signed cert for DNS core only"
echo "  2) Internet - server with public IP (80, 443, 853, 5300 TCP; 53 UDP) - Let's Encrypt"
read -r -p "Choice [1/2] (default 1): " MODE
MODE="${MODE:-1}"
case "$MODE" in
  1) MODE=local ;;
  2) MODE=internet ;;
  *) echo "Invalid choice. Use 1 or 2."; exit 1 ;;
esac
echo ""

if [[ "$MODE" == "local" ]]; then
  read -r -p "Domain name (e.g. test.com) [localhost]: " DOMAIN
  DOMAIN="${DOMAIN:-localhost}"
else
  read -r -p "Domain name (e.g. test.com): " DOMAIN
  [[ -z "$DOMAIN" ]] && { echo "Domain is required."; exit 1; }
fi
DOMAIN="${DOMAIN%.}"
[[ -z "$DOMAIN" ]] && { echo "Domain is required."; exit 1; }

API_DOMAIN="api.${DOMAIN}"
DNS_DOMAIN="dns.${DOMAIN}"
ADMIN_DOMAIN="admin.${DOMAIN}"
echo "  → DOMAIN: ${DOMAIN}  |  API: ${API_DOMAIN}  |  DNS: ${DNS_DOMAIN}  |  Admin: ${ADMIN_DOMAIN}"
echo ""

if [[ "$MODE" == "local" ]]; then
  read -r -p "LAN IP for this host (block page) [127.0.0.1]: " IP_ADDRESS
  IP_ADDRESS="${IP_ADDRESS:-127.0.0.1}"
else
  read -r -p "Public IP of this server: " IP_ADDRESS
  [[ -z "$IP_ADDRESS" ]] && { echo "Public IP is required."; exit 1; }
  read -r -p "Email for Let's Encrypt: " EMAIL
  [[ -z "$EMAIL" ]] && { echo "Email is required."; exit 1; }
  echo "Force new certificate generation (e.g. after key rotation / leak)?"
  read -r -p "  [y/N]: " FORCE_RENEW
  FORCE_RENEW="${FORCE_RENEW:-n}"
  [[ "$FORCE_RENEW" =~ ^[yY] ]] && CERTBOT_EXTRA="--force-renewal" || CERTBOT_EXTRA=""
fi
echo ""

gen_self_signed() {
  local dir="$1"
  local cn="$2"
  local san="$3"
  mkdir -p "$dir"
  openssl genrsa -out "${dir}/privkey.pem" 2048
  openssl req -new -x509 -key "${dir}/privkey.pem" \
    -out "${dir}/fullchain.pem" -days 825 \
    -subj "/CN=${cn}" -addext "subjectAltName=${san}"
}

if [[ "$MODE" == "local" ]]; then
  echo "Generating self-signed certificate for DNS core (DoT/DoH) ..."
  gen_self_signed "${SSL_DIR}/dns" "$DNS_DOMAIN" "DNS:${DNS_DOMAIN}"
  echo "  → ${SSL_DIR}/dns/ (used by dnsdist for ports 853/tcp and 5300/tcp)"
  echo ""
  echo "No certificates needed for API and Admin (running over HTTP locally)."

  TLS_MODE="off"
  API_SCHEME="http://"
  ADMIN_SCHEME="http://"
  API_URL="http://${API_DOMAIN}/"
else
  echo "Using Let's Encrypt. Ensure ports 80 and 443 are free."
  LE_LIVE="/etc/letsencrypt/live"
  for name in "$API_DOMAIN" "$DNS_DOMAIN" "$ADMIN_DOMAIN"; do
    echo "  Certificate for ${name} ..."
    sudo certbot certonly --standalone --non-interactive --agree-tos -m "$EMAIL" -d "$name" $CERTBOT_EXTRA
  done
  echo "  Self-signed for IP (block page): ${IP_ADDRESS} ..."
  mkdir -p "${SSL_DIR}/api" "${SSL_DIR}/dns" "${SSL_DIR}/admin" "${SSL_DIR}/ip"
  sudo cp "${LE_LIVE}/${API_DOMAIN}/fullchain.pem" "${LE_LIVE}/${API_DOMAIN}/privkey.pem" "${SSL_DIR}/api/"
  sudo cp "${LE_LIVE}/${DNS_DOMAIN}/fullchain.pem" "${LE_LIVE}/${DNS_DOMAIN}/privkey.pem" "${SSL_DIR}/dns/"
  sudo cp "${LE_LIVE}/${ADMIN_DOMAIN}/fullchain.pem" "${LE_LIVE}/${ADMIN_DOMAIN}/privkey.pem" "${SSL_DIR}/admin/"
  gen_self_signed "${SSL_DIR}/ip" "$IP_ADDRESS" "IP:${IP_ADDRESS}"

  TLS_MODE="on"
  API_SCHEME=""
  ADMIN_SCHEME=""
  API_URL="https://${API_DOMAIN}/"
fi
echo ""

API_SECRET="$(openssl rand -base64 32)"
cat > "$ENV_FILE" << EOF
# Generated by prerequisites.sh (used by docker-compose and capy_api)
# API/DNS/ADMIN hostnames are always api.\$DOMAIN, dns.\$DOMAIN, admin.\$DOMAIN
DOMAIN=${DOMAIN}
IP_ADDRESS=${IP_ADDRESS}
API_SECRET=${API_SECRET}
TLS_MODE=${TLS_MODE}
API_SCHEME=${API_SCHEME}
ADMIN_SCHEME=${ADMIN_SCHEME}
API_URL=${API_URL}
EOF
echo "Wrote ${ENV_FILE}"
echo ""
echo "Next: from this directory run:  docker compose up -d --build"
echo "      (or from elsewhere:       docker compose --env-file ${ENV_FILE} -f ${ROOT}/docker-compose.yaml up -d --build)"
