#!/usr/bin/env bash
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SSL_DIR="${ROOT}/resources/ssl"
ENV_FILE="${ROOT}/.env"
# Output layout: resources/ssl/{api,dns,admin,ip}/*.pem (fullchain.pem + privkey.pem each)

echo "=============================================="
echo "  Capy Privacy - Setup & Start"
echo "=============================================="
echo ""

echo "Where will this run?"
echo "  1) Local only (LAN) - self-signed certificates"
echo "  2) Internet - server with public IP (80, 443, 853, 5300 TCP; 53 UDP) - Let's Encrypt"
read -r -p "Choice [1/2]: " MODE
case "$MODE" in
  1) MODE=local ;;
  2) MODE=internet ;;
  *) echo "Invalid choice. Use 1 or 2."; exit 1 ;;
esac
echo ""

read -r -p "Domain name (e.g. test.com): " BASE_DOMAIN
BASE_DOMAIN="${BASE_DOMAIN%.}"
[[ -z "$BASE_DOMAIN" ]] && { echo "Domain is required."; exit 1; }

API_DOMAIN="api.${BASE_DOMAIN}"
DNS_DOMAIN="dns.${BASE_DOMAIN}"
ADMIN_DOMAIN="admin.${BASE_DOMAIN}"
echo "  → API: ${API_DOMAIN}  |  DNS: ${DNS_DOMAIN}  |  Admin: ${ADMIN_DOMAIN}"
echo ""

if [[ "$MODE" == "local" ]]; then
  read -r -p "LAN IP for this host (block page) [127.0.0.1]: " IP_ADDRESS
  IP_ADDRESS="${IP_ADDRESS:-127.0.0.1}"
else
  read -r -p "Public IP of this server: " IP_ADDRESS
  [[ -z "$IP_ADDRESS" ]] && { echo "Public IP is required."; exit 1; }
  read -r -p "Email for Let's Encrypt: " EMAIL
  [[ -z "$EMAIL" ]] && { echo "Email is required."; exit 1; }
fi
echo ""

gen_self_signed() {
  local dir="$1"
  local cn="$2"
  local san="$3"
  mkdir -p "$dir"
  openssl genrsa -out "${dir}/privkey.pem" 2048
  openssl req -new -x509 -key "${dir}/privkey.pem" \
    -out "${dir}/fullchain.pem" -days 825 \
    -subj "/CN=${cn}" -addext "subjectAltName=${san}"
}

if [[ "$MODE" == "local" ]]; then
  echo "Generating self-signed certificates in ${SSL_DIR} ..."
  mkdir -p "${SSL_DIR}/api" "${SSL_DIR}/dns" "${SSL_DIR}/admin" "${SSL_DIR}/ip"
  gen_self_signed "${SSL_DIR}/api" "$API_DOMAIN" "DNS:${API_DOMAIN}"
  gen_self_signed "${SSL_DIR}/dns" "$DNS_DOMAIN" "DNS:${DNS_DOMAIN}"
  gen_self_signed "${SSL_DIR}/admin" "$ADMIN_DOMAIN" "DNS:${ADMIN_DOMAIN}"
  gen_self_signed "${SSL_DIR}/ip" "$IP_ADDRESS" "IP:${IP_ADDRESS}"
else
  echo "Using Let's Encrypt. Ensure ports 80 and 443 are free."
  LE_LIVE="/etc/letsencrypt/live"
  for name in "$API_DOMAIN" "$DNS_DOMAIN" "$ADMIN_DOMAIN"; do
    echo "  Certificate for ${name} ..."
    sudo certbot certonly --standalone --non-interactive --agree-tos -m "$EMAIL" -d "$name"
  done
  echo "  Self-signed for IP (block page): ${IP_ADDRESS} ..."
  mkdir -p "${SSL_DIR}/api" "${SSL_DIR}/dns" "${SSL_DIR}/admin" "${SSL_DIR}/ip"
  sudo cp "${LE_LIVE}/${API_DOMAIN}/fullchain.pem" "${LE_LIVE}/${API_DOMAIN}/privkey.pem" "${SSL_DIR}/api/"
  sudo cp "${LE_LIVE}/${DNS_DOMAIN}/fullchain.pem" "${LE_LIVE}/${DNS_DOMAIN}/privkey.pem" "${SSL_DIR}/dns/"
  sudo cp "${LE_LIVE}/${ADMIN_DOMAIN}/fullchain.pem" "${LE_LIVE}/${ADMIN_DOMAIN}/privkey.pem" "${SSL_DIR}/admin/"
  gen_self_signed "${SSL_DIR}/ip" "$IP_ADDRESS" "IP:${IP_ADDRESS}"
fi
echo ""

cat > "$ENV_FILE" << EOF
# Generated by start.sh (used by docker-compose and Caddy)
API_DOMAIN=${API_DOMAIN}
DNS_DOMAIN=${DNS_DOMAIN}
ADMIN_DOMAIN=${ADMIN_DOMAIN}
IP_ADDRESS=${IP_ADDRESS}
EOF
echo "Wrote ${ENV_FILE}"
echo "You need to manually start the Docker stack..."
# docker compose up --build -d
# echo ""
# echo "Done. Ports: 80, 443 (admin), 53/udp, 853, 5300 (DNS)."
